### PR TITLE
Fix typo.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ElizabethmParker** [comment]
yes this is my boyfriend looking in on everythhing I do and u guys helped him hack into my phone so if u could pleas let me know something it would be great and plz let me know if he has videos out there as well

**Comment by ghost** [comment]
:|

**Comment by ghost** [comment]
Grammar Nazis never win apparently.

**Comment by nicholaschum** [comment]
@ElizabethmParker what in god's name are you talking about? Like for real...?

**Comment by pichord** [comment]
@ElizabethmParker I don't think anyone has any knowledge of what you've just said, but if your boyfriend was able to make you comment to a pull request on GitHub, I really hope he doesn't make you go through each and ever line of code here. 
It'll take weeks,  and when you'll be busy reading code that's when your boyfriend will have a peek into your mobile. 
:( all the best to you

**Comment by ghost** [comment]
@nicholaschum @thecyberfibre I don't really understand how this is getting attention 21 days after it happened, but whatever XD

**Comment by msfjarvis** [comment]
LMAO what even happened here :rofl:

**Comment by pichord** [comment]
@MSF-Jarvis,  @nolanroell motivated @ElizabethmParker to comment is a rather... Interesting way.

**Comment by ghost** [comment]
@MSF-Jarvis Sit down, its story time. It all started with a typo...

**Comment by msfjarvis** [comment]
This made about zero sense, so I'll just go write my math exam, when I'm back, you explain this over Telegram @thecyberfibre

**Comment by pichord** [comment]
@MSF-Jarvis sure thing, buddy. The only problem is that you'd be half dead

**Comment by poad42** [comment]
@thecyberfibre Pretty sure its a bot

**Pull request closed without merging**
