### PR TITLE
Put all configs in one file

### PR DESCRIPTION
**Pull request by AllanWang**
Instead of having something in strings.xml and some things in the manifest, just redirect it all to one file for easy access. I also have a few comments:

* If users are supposed to update the plugin meta data number for each aar update, you might want to find some other way to embed it automatically
* If the substrate.aar is meant to be private, we can still access all the classes from it
* If it's not meant to be private, you can make an actual library and just have a dependency via jitpack, which makes it easier to update (we update the number rather than download a new aar).
* If you keep on committing new aars with each test and asking themers to fork the project, you're making them download every old aar that was uploaded.
* You might also want to update the readme if you accept this, and also give more documentation as to what substrate is and why it is disabled as a default.

### CODE REVIEW

**Comment by Trafalgar-Square** [comment]
@AllanWang Hello

**Comment by nicholaschum** [comment]
@AllanWang Users aren't meant to update the metadata version of the plugin.

**Comment by nicholaschum** [comment]
@AllanWang Regarding the aar. Everything goes through the aar. No question about it. It's how the theme launches and enabling a flag would just enable one of many substrate functions regarding antipiracy.

**Comment by AllanWang** [comment]
@nicholaschum so let's say I forked the project way back when the plugin was still 2.x. Now that I'm updating it again, am I not supposed to make it what it is now? (as if I just forked it again). And if that's what substrate does, maybe you could combine the two antipiracy booleans.

**Comment by nicholaschum** [comment]
@AllanWang Just cherry pick the changes. Substrate doesn't use booleans, it's a direct static library that handles all the launching of Substratum's InformationActivity. It's a good idea to have Substrate add the metadata automatically yes, I'll look into it very soon.

**Comment by AllanWang** [comment]
@nicholaschum I'm referring to this [boolean](https://github.com/TeamSubstratum/SubstratumThemeTemplate/blob/master/app/build.gradle#L31). There isn't any documentation as to what it does.

**Comment by nicholaschum** [comment]
@AllanWang Third Step: https://github.com/TeamSubstratum/SubstratumThemeTemplate/blob/master/README.md#getting-started-with-antipiracy

**Comment by AllanWang** [comment]
@nicholaschum ah oops. Didn't find it when I searched for the boolean name. Thanks

**Pull request closed without merging**
