### PR TITLE
Remove extra closing braces

### PR DESCRIPTION
**Pull request by nealgosalia**

### CODE REVIEW

**Comment by akhilnarang** [comment]
@nealgosalia Wew

**Comment by artem** [comment]
Patch Set 1: Code-Review+2 Verified+1
Ready to merge

**Comment by spannaa** [comment]
I may well be wrong, but isn't it the closing brace on line #216 that needs to go, not the one on line #230 ?  

I missed the last brace when I removed:

https://github.com/substratum/template/blob/115a23d783dfca50eae3f2dac98c4caaaa1e421c/app/src/main/java/substratum/theme/template/SubstratumLauncher.kt#L217-L228

**Comment by nathanchance** [comment]
@spannaa Yes, you are right.

1f9ae5acd9cb55eb189fe313daea4492216a0682 is the problem commit.

**Comment by nealgosalia** [comment]
Yes, I seem to have made a mistake while making a PR from my phone. Thanks @spannaa !

**Pull request closed without merging**
