### PR TITLE
[WiP] Move all variables to gradle file

### PR DESCRIPTION
**Pull request by andrzejressel**
Themers shouldn't care if plugin is written in Java, Kotlin, C++ or Brainfuck. They just need simple way to include their's theme data. Do make it easier let's make new file `variables.gradle` where thety could enter this data and files for Java and C will be generated from it.

Before merging this PR should be checked and accepted by themers.

### CODE REVIEW

**Review by llevo3 — COMMENTED** [review]
Fine with me

**Comment by ivaniskandar** [comment]
The idea is good but can you also try to move the generated IV_KEY and DECRYPTION_KEY from BuildConfig to the header file too? It would be great if we can put all the anti-piracy related values there.

**Comment by andrzejressel** [comment]
@iskandar1023 It's much harder to add byte arrays there. For now I just want to support strings and booleans.

**Comment by ivaniskandar** [comment]
Okay, just clean up the changes and maybe rebase the branch instead of merging (so there will be no blank merge commit) before we continue further.

**Comment by andrzejressel** [comment]
@iskandar1023 When merging you can squash changes so there will be only one commit: 
image

**Comment by ivaniskandar** [comment]
Sure just finish the work then.

**Pull request closed without merging**
